# docker build -t this
# docker-compose -f docker-compose.test.yml up --exit-code-from sut
version: "3.6"
services:
  jenkins:
    image: tomdesinto/jenkins-dsl-ready

  sut:
    image: this
    depends_on:
      - jenkins
    volumes:
      - ./utils/:/utils/
    links:
      - jenkins
    command: /utils/wait-for-it.sh --host=jenkins --port=8080 --strict --timeout=30 -- /jenkins_remote_trigger.sh --host=http://jenkins:8080/ --jobname=SeedJob --timeout=2